services:

  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: dev.Dockerfile
    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - "3000:3000"
    networks:
      - hub
    depends_on:
      - postgres

  postgres:
    networks:
      - hub
    image: postgres:16-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myF4vePlaceBase
      POSTGRES_DB: postgres

  adminer:
    networks:
      - hub
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  hub:
    name: hub